providers:
#  dotenv_1:
#    kind: dotenv
#    maps:
#    - id: ''
#      path: /home/fodurrr/dotfiles/.config/fabric/.env
#  hashicorp_1:
#    kind: hashicorp
#    maps:
#    - id: ''
#      path: secrets/apps/fabric/secret/ANTHROPIC_API_KEY
#    env:
#      AZURE_OPENAI_API_VERSION:
#        path: projects/vfarcic/secrets/azure-openai-api-version/versions/1
