# =============================================================================
# Mise Helpers
# =============================================================================

# Track installed apps to avoid duplicates (for dependency resolution)
# Using string-based tracking for bash 3.2 compatibility (macOS default)
INSTALLED_APPS=""

# Install a mise app with dependency resolution
install_mise_app() {
    local app_key="$1"

    # Skip if already processed this session (pipe delimiters prevent partial matches)
    [[ "$INSTALLED_APPS" == *"|$app_key|"* ]] && return 0

    if ! command -v mise >/dev/null 2>&1; then
        log_error "mise is not installed but required for $app_key"
        return 1
    fi

    # Check for dependency (install silently if needed)
    local dep
    dep=$(get_app_prop "$app_key" "depends_on")
    if [[ -n "$dep" ]]; then
        if ! install_mise_app "$dep"; then
            log_error "Failed dependency '$dep' required by '$app_key'"
            return 1
        fi
    fi

    # Mark as processed
    INSTALLED_APPS="${INSTALLED_APPS}|${app_key}|"

    # Get app details
    local name
    name=$(get_app_prop "$app_key" "name")
    [[ -z "$name" ]] && name="$app_key"
    local version
    version=$(get_app_prop "$app_key" "version")
    [[ -z "$version" ]] && version="latest"

    # Check if already installed with correct version
    # IMPORTANT: mise current returns configured version even if not installed!
    # We must check mise ls for "(missing)" to detect actual installation state
    local installed_version=""
    local ls_output
    ls_output=$(mise ls "$name" 2>/dev/null || true)
    # Only trust mise current if tool exists AND is not marked as missing
    if [[ -n "$ls_output" ]]; then
        if [[ "$ls_output" == *"(missing)"* ]]; then
            : # Tool is in config but not installed - leave installed_version empty
        else
            installed_version=$(mise current "$name" 2>/dev/null || true)
        fi
    fi

    if [[ -n "$installed_version" ]]; then
        if [[ "$version" == "latest" ]]; then
            # For "latest", check if there's a newer version available
            local latest_version
            latest_version=$(mise latest "$name" 2>/dev/null || true)
            if [[ "$installed_version" == "$latest_version" ]]; then
                add_to_summary SKIPPED "$name" "$app_key"
                return 0
            else
                log_info "$name@$installed_version outdated (latest: $latest_version), upgrading..."
            fi
        elif [[ "$version" == "lts" || "$version" == "stable" ]]; then
            # For "lts" or "stable", if any version is installed, consider it good
            # These are moving targets, no need to constantly reinstall
            add_to_summary SKIPPED "$name" "$app_key"
            return 0
        elif [[ "$installed_version" == "$version"* ]]; then
            # Prefix match: "3.14.2" starts with "3.14" → skip
            # Also handles exact matches: "3.14.2" starts with "3.14.2" → skip
            add_to_summary SKIPPED "$name" "$app_key"
            return 0
        else
            log_info "$name@$installed_version installed, but $version requested, installing..."
        fi
    else
        log_success "Installing $name@$version..."
    fi

    # Capture both stdout and stderr to show errors on failure
    local install_output
    if install_output=$(mise install "$name@$version" 2>&1); then
        add_to_summary INSTALLED "$name" "$app_key"
        return 0
    else
        log_error "Failed to install $name"
        # Show first line of error to help debugging
        local error_line
        error_line=$(echo "$install_output" | grep -i "error\|failed\|not found" | head -1)
        [[ -n "$error_line" ]] && echo "      $error_line"
        return 1
    fi
}

# Generate mise config based on selected profiles
# This creates the config in the dotfiles repo, which then gets symlinked by stow
generate_mise_config() {
    local config_file="$DOTFILES_DIR/mise/.config/mise/config.toml"
    mkdir -p "$(dirname "$config_file")"

    log_info "Generating mise config for selected profiles..."

    # Header
    cat > "$config_file" << 'EOF_MISE'
# =============================================================================
# Mise Config - Auto-generated by install.sh
# =============================================================================
# This file is regenerated based on selected profile(s).
# To add tools permanently, edit apps.toml with type = "mise"
# =============================================================================

[tools]
EOF_MISE

    # Add tools from apps.toml that match selected profiles and type=mise
    local app_key
    for app_key in $(get_all_apps); do
        if app_selected_for_install "$app_key"; then
            local type
            type=$(get_app_prop "$app_key" "type")
            if [[ "$type" == "mise" ]]; then
                local name
                name=$(get_app_prop "$app_key" "name")
                [[ -z "$name" ]] && name="$app_key"
                local version
                version=$(get_app_prop "$app_key" "version")
                [[ -z "$version" ]] && version="latest"
                echo "$name = \"$version\"" >> "$config_file"
            fi
        fi
    done

    # Settings
    cat >> "$config_file" << 'EOF_MISE'

[settings]
log_level = "info"
experimental = true
EOF_MISE

    log_success "Generated mise config with $(grep -c '=' "$config_file" 2>/dev/null || echo 0) tools"
}
